export interface Category {
  id: string;
  title: string;
}

export interface ProductSpec {
  label: string;
  value: string;
}

export interface Product {
  id: string;
  title: string;
  categoryId: string;
  priceRub: number | null;
  url: string;
  availability: string;
  specs: ProductSpec[];
}

export interface Catalog {
  supplierName: string;
  supplierHomepageUrl: string;
  discountPercentForCeilingOrder: number;
  disclaimer: string;
  updatedAt: string;
  categories: Category[];
  products: Product[];
}

export const catalog: Catalog = {
  supplierName: "eksmarket.ru",
  supplierHomepageUrl: "https://eksmarket.ru",
  discountPercentForCeilingOrder: 15,
  disclaimer:
    "Цены и наличие могут меняться. Подтвердим актуальную цену при оформлении заявки. Скидка 15% действует при заказе натяжных потолков.",
  updatedAt: "2026-04-09",
  categories: [
    { id: "clarus-48v", title: "Система CLARUS 48V" },
    { id: "colibri-220v", title: "Система COLIBRI 220V" },
    { id: "odnofaznaya-220v", title: "Однофазная трековая система 220V" },
  ],
  products: [
    // === CLARUS 48V ===
    {
      id: "0У-00006634",
      title: "CLARUS трековый профиль под гарпун 48V чёрный, 2000×60×33 мм",
      categoryId: "clarus-48v",
      priceRub: 8000,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-trekovyy-profil-pod-garpun-48v-chyernyy-2000-60-33-mm-5-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "трековый профиль под гарпун" },
        { label: "Напряжение", value: "48V" },
        { label: "Цвет", value: "чёрный" },
        { label: "Размер", value: "2000×60×33 мм" },
      ],
    },
    {
      id: "0У-00006633",
      title: "CLARUS трековый профиль под гарпун 48V чёрный, 1000×60×33 мм",
      categoryId: "clarus-48v",
      priceRub: 4000,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-trekovyy-profil-pod-garpun-48v-chyernyy-1000-60-33-mm-5-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "трековый профиль под гарпун" },
        { label: "Напряжение", value: "48V" },
        { label: "Цвет", value: "чёрный" },
        { label: "Размер", value: "1000×60×33 мм" },
      ],
    },
    {
      id: "0У-00002305",
      title: "CLARUS Магнитный ультратонкий шинопровод 48V белый, 1000 мм",
      categoryId: "clarus-48v",
      priceRub: 990,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-magnitnyy-ultratonkiy-shinoprovod-48v-belyy-1000-mm-40-sht/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "шинопровод магнитный ультратонкий" },
        { label: "Напряжение", value: "48V" },
        { label: "Цвет", value: "белый" },
        { label: "Размер", value: "1000×25×6 мм" },
      ],
    },
    {
      id: "0У-00002307",
      title: "CLARUS Магнитный ультратонкий шинопровод 48V белый, 2000 мм",
      categoryId: "clarus-48v",
      priceRub: 1890,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-magnitnyy-ultratonkiy-shinoprovod-48v-belyy-2000-mm-40-sht/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "шинопровод магнитный ультратонкий" },
        { label: "Напряжение", value: "48V" },
        { label: "Цвет", value: "белый" },
        { label: "Размер", value: "2000×25×6 мм" },
      ],
    },
    {
      id: "0У-00006635",
      title: "CLARUS торцевая заглушка для трекового профиля черная",
      categoryId: "clarus-48v",
      priceRub: 150,
      url: "https://eksmarket.ru/catalog/sistema-clarus/clarus-tortsevaya-zaglushka-dlya-trekovogo-profilya-chernaya-komplekt-na-1-storonu/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "торцевая заглушка" },
        { label: "Назначение", value: "для трекового профиля" },
        { label: "Цвет", value: "черная" },
      ],
    },
    {
      id: "0У-00006636",
      title: "CLARUS соединитель угловой внутренний для трекового профиля чёрный",
      categoryId: "clarus-48v",
      priceRub: 680,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-soedinitel-uglovoy-vnutrenniy-dlya-trekovogo-profilya-chyernyy-50-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "соединитель угловой внутренний" },
        { label: "Назначение", value: "для трекового профиля" },
        { label: "Цвет", value: "чёрный" },
      ],
    },
    {
      id: "0У-00002330",
      title: "CLARUS Коннектор прямой 48V для магнитного ультратонкого шинопровода, черный",
      categoryId: "clarus-48v",
      priceRub: 370,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-konnektor-pryamoy-48v-dlya-magnitnogo-ultratonkogo-shinoprovoda-chernyy-200-sht-n/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
        { label: "Размер", value: "20×25×5 мм" },
      ],
    },
    {
      id: "0У-00002321",
      title: "CLARUS Коннектор Т-образный 48V для магнитного ультратонкого шинопровода, черный",
      categoryId: "clarus-48v",
      priceRub: 540,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-konnektor-t-obraznyy-48v-dlya-magnitnogo-ultratonkogo-shinoprovoda-chernyy-100-sht-n/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
        { label: "Размер", value: "75×50×5 мм" },
      ],
    },
    {
      id: "0У-00002327",
      title: "CLARUS Ввод питания (скрытый) 48V для магнитного ультратонкого шинопровода, черный",
      categoryId: "clarus-48v",
      priceRub: 540,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-vvod-pitaniya-skrytyy-48v-dlya-magnitnogo-ultratonkogo-shinoprovoda-chernyy-100-sht-n/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
        { label: "Размер", value: "40×25×5 мм" },
      ],
    },
    {
      id: "0У-00002325",
      title: "CLARUS Соединитель потолок-стена 48V для магнитного ультратонкого шинопровода, черный",
      categoryId: "clarus-48v",
      priceRub: 702,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-soedinitel-potolok-stena-48v-dlya-magnitnogo-ultratonkogo-shinoprovoda-chernyy-100-sht-n/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
        { label: "Размер", value: "50×50×25 мм" },
      ],
    },
    {
      id: "0У-00002310",
      title: "CLARUS блок питания для скрытого монтажа 200 W, 48V",
      categoryId: "clarus-48v",
      priceRub: 1530,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-blok-pitaniya-dlya-skrytogo-montazha-200-w-48v-50-sht/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Мощность", value: "200W" },
        { label: "Материал корпуса", value: "Металл" },
        { label: "Размер", value: "185×48×24 мм" },
      ],
    },
    {
      id: "0У-00002303",
      title: "CLARUS SMART Магнитный ультратонкий трековый светильник SPOT белый, 12W, 2700~6000K",
      categoryId: "clarus-48v",
      priceRub: 4590,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-smart-magnitnyy-ultratonkiy-trekovyy-svetilnik-spot-belyy-12w-2700-6000k-40-sht/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Мощность", value: "12W" },
        { label: "Световой поток", value: "1100Lm" },
        { label: "Температура свечения", value: "2700–6000K" },
      ],
    },
    {
      id: "0У-00002299",
      title: "CLARUS SMART Магнитный ультратонкий трековый светильник ACCENT белый, 18W, 2700~6000K",
      categoryId: "clarus-48v",
      priceRub: 2836,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-smart-magnitnyy-ultratonkiy-trekovyy-svetilnik-aktsent-belyy-18w-2700-6000k-50-sht/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Мощность", value: "18W" },
        { label: "Световой поток", value: "1680Lm" },
        { label: "Температура свечения", value: "2700–6000K" },
      ],
    },
    {
      id: "0У-00002291",
      title: "CLARUS SMART Магнитный ультратонкий трековый светильник NORD белый, 18W, 2700~6000K",
      categoryId: "clarus-48v",
      priceRub: 4500,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-smart-magnitnyy-ultratonkiy-trekovyy-svetilnik-nord-belyy-18w-2700-6000k-50-sht/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Мощность", value: "18W" },
        { label: "Световой поток", value: "1680Lm" },
        { label: "Температура свечения", value: "2700–6000K" },
      ],
    },
    {
      id: "0У-00004525",
      title: "CLARUS Магнитный трековый светильник SATURN белый, 7W, 4000К, D180×46 мм",
      categoryId: "clarus-48v",
      priceRub: 1800,
      url: "https://eksmarket.ru/catalog/sistema-clarus/klarus-magnitnyy-trekovyy-svetilnik-saturn-belyy-7w-4000k-d180kh46mm-40-sht/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "48V" },
        { label: "Мощность", value: "7W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Размер", value: "D180×46 мм" },
      ],
    },

    // === COLIBRI 220V ===
    {
      id: "0У-00001341",
      title: "COLIBRI трековый шинопровод 220V чёрный, 2000×31×57 мм",
      categoryId: "colibri-220v",
      priceRub: 5082,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-shinoprovod-220v-chyernyy-2000-31-57-mm-5-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Металл" },
      ],
    },
    {
      id: "0У-00001340",
      title: "COLIBRI трековый шинопровод 220V чёрный, 1000×31×57 мм",
      categoryId: "colibri-220v",
      priceRub: 2090,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-shinoprovod-220v-chyernyy-1000-31-57-mm-5-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Металл" },
      ],
    },
    {
      id: "0У-00001343",
      title: "COLIBRI трековый ввод питания 220V чёрный",
      categoryId: "colibri-220v",
      priceRub: 447,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-vvod-pitaniya-220v-chyernyy-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
      ],
    },
    {
      id: "0У-00001344",
      title: "COLIBRI трековый прямой коннектор 220V чёрный",
      categoryId: "colibri-220v",
      priceRub: 469,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-pryamoy-konnektor-220v-chyernyy-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
      ],
    },
    {
      id: "0У-00001342",
      title: "COLIBRI трековый угловой коннектор (гибкий) 220V чёрный",
      categoryId: "colibri-220v",
      priceRub: 902,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-uglovoy-konnektor-gibkiy-220v-chyernyy-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
      ],
    },
    {
      id: "0У-00006090",
      title: "COLIBRI трековый профиль под гарпун 220V чёрный, 2000×62×51 мм",
      categoryId: "colibri-220v",
      priceRub: 7400,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-profil-pod-garpun-220v-chyernyy-2000-62-51-mm-5-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "Трековый профиль под гарпун" },
        { label: "Напряжение", value: "220V" },
        { label: "Цвет", value: "чёрный" },
        { label: "Размер", value: "2000×62×51 мм" },
      ],
    },
    {
      id: "0У-00006089",
      title: "COLIBRI трековый профиль под гарпун 220V чёрный, 1000×62×51 мм",
      categoryId: "colibri-220v",
      priceRub: 3700,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-profil-pod-garpun-220v-chyernyy-1000-62-51-mm-5-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "Трековый профиль под гарпун" },
        { label: "Напряжение", value: "220V" },
        { label: "Цвет", value: "чёрный" },
        { label: "Размер", value: "1000×62×51 мм" },
      ],
    },
    {
      id: "0У-00006986",
      title: "COLIBRI трековый профиль под гарпун 220V чёрный, 3000×62×51 мм",
      categoryId: "colibri-220v",
      priceRub: 11100,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-profil-pod-garpun-220v-chyernyy-3000-62-51-mm-5-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "Трековый профиль под гарпун" },
        { label: "Напряжение", value: "220V" },
        { label: "Цвет", value: "чёрный" },
        { label: "Размер", value: "3000×62×51 мм" },
      ],
    },
    {
      id: "0У-00006091",
      title: "COLIBRI торцевая заглушка для трекового профиля черная",
      categoryId: "colibri-220v",
      priceRub: 200,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/colibri-tortsevaya-zaglushka-dlya-trekovogo-profilya-chernaya-2-sht-up/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "торцевая заглушка" },
        { label: "Назначение", value: "для трекового профиля" },
        { label: "Цвет", value: "черная" },
      ],
    },
    {
      id: "0У-00006095",
      title: "COLIBRI соединитель угловой внутренний для трекового профиля под гарпун чёрный",
      categoryId: "colibri-220v",
      priceRub: 560,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-soedinitel-uglovoy-vnutrenniy-dlya-trekovogo-profilya-pod-garpun-chyernyy-50-sht-kor-v/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "соединитель угловой внутренний" },
        { label: "Назначение", value: "для трекового профиля под гарпун" },
        { label: "Цвет", value: "чёрный" },
      ],
    },
    {
      id: "0У-00004820",
      title: "Подвес COLIBRI черный",
      categoryId: "colibri-220v",
      priceRub: 582,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/podves-kolibri-chernyy-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "регулируемый подвес" },
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
      ],
    },
    {
      id: "0У-00001339",
      title: "COLIBRI трековый светильник LONDON черный, 20W, 4000K, 1800ЛМ, D410×25×40",
      categoryId: "colibri-220v",
      priceRub: 4510,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-svetilnik-london-chernyy-20w-4000k-1800lm-d410-25-40-20-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Мощность", value: "20W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Световой поток", value: "1800Lm" },
      ],
    },
    {
      id: "0У-00001338",
      title: "COLIBRI трековый светильник LONDON черный, 10W, 4000K, 900ЛМ, D220×25×40",
      categoryId: "colibri-220v",
      priceRub: 1540,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-svetilnik-london-chernyy-10w-4000k-900lm-d220-25-40-30-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Мощность", value: "10W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Световой поток", value: "900Lm" },
      ],
    },
    {
      id: "0У-00001335",
      title: "COLIBRI трековый светильник RIO черный, 12W, 4000K, 1100ЛМ, D50×100",
      categoryId: "colibri-220v",
      priceRub: 3080,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-trekovyy-svetilnik-rio-chernyy-12w-4000k-1100lm-d50-100-20-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Мощность", value: "12W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Световой поток", value: "1100Lm" },
      ],
    },
    {
      id: "0У-00002005",
      title: "COLIBRI SMART Конвертер WI-FI для трековой системы",
      categoryId: "colibri-220v",
      priceRub: 3300,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/colibri-smart-konverter-wi-fi-dlya-trekovoy-sistemy-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Цвет", value: "Белый" },
        { label: "Материал", value: "Пластик" },
        { label: "Размер", value: "65×65×14.5 мм" },
      ],
    },
    {
      id: "0У-00002332",
      title: "COLIBRI Пульт для управления смарт системы черный",
      categoryId: "colibri-220v",
      priceRub: 1540,
      url: "https://eksmarket.ru/catalog/sistema-colibri-220v/kolibri-pult-dlya-upravleniya-smart-sistemy-chernyy-200-sht/",
      availability: "нет данных",
      specs: [
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Материал корпуса", value: "Пластик" },
      ],
    },

    // === Однофазная трековая система 220V ===
    {
      id: "0У-00006342",
      title: "Однофазный шинопровод ART 220V черный, 3000×34×19 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 1860,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-shinoprovod-art-220v-chernyy-3000-34-19-mm-20-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет", value: "черный" },
        { label: "Размер", value: "3000×34×19 мм" },
      ],
    },
    {
      id: "0У-00001355",
      title: "Однофазный шинопровод ART 220V чёрный, 2000×34×19 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 1280,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-shinoprovod-art-220v-chyernyy-2000-34-19-mm-20-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Тип крепления", value: "Накладной" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Размер", value: "2000×34×19 мм" },
      ],
    },
    {
      id: "0У-00001356",
      title: "Однофазный шинопровод ART 220V белый, 2000×34×19 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 1280,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-shinoprovod-art-220v-belyy-2000x34x19mm-20-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Тип крепления", value: "Накладной" },
        { label: "Цвет корпуса", value: "Белый" },
        { label: "Размер", value: "2000×34×19 мм" },
      ],
    },
    {
      id: "0У-00001359",
      title: "Однофазный коннектор 220V L-образный, чёрный, 69×69 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 184,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-konnektor-220v-l-obraznyy-chyernyy-69-69-mm-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Размер", value: "69×69 мм" },
      ],
    },
    {
      id: "0У-00001361",
      title: "Однофазный коннектор 220V T-образный, чёрный, 107×71 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 280,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-konnektor-220v-t-obraznyy-chyernyy-107-71-mm-50-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Размер", value: "107×71 мм" },
      ],
    },
    {
      id: "0У-00001363",
      title: "Однофазный коннектор 220V X-образный, чёрный, 107×107 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 320,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-konnektor-220v-kh-obraznyy-chyernyy-107-107-mm-50-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Размер", value: "107×107 мм" },
      ],
    },
    {
      id: "0У-00001367",
      title: "Однофазный коннектор 220V тонкий гибкий, чёрный",
      categoryId: "odnofaznaya-220v",
      priceRub: 290,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-konnektor-220v-tonkiy-gibkiy-chyernyy-200-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
      ],
    },
    {
      id: "0У-00001365",
      title: "Однофазный коннектор 220V PRO гибкий, чёрный, 280×34 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 1084,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/odnofaznyy-konnektor-220v-pro-gibkiy-chyernyy-280-34-mm-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Размер", value: "280×34 мм" },
      ],
    },
    {
      id: "0У-00004819",
      title: "Подвес PRO черный",
      categoryId: "odnofaznaya-220v",
      priceRub: 456,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/podves-pro-chernyy-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Цвет корпуса", value: "Черный" },
      ],
    },
    {
      id: "0У-00001369",
      title: "Тросовый подвес для однофазного шинопровода ART чёрный, 145 см",
      categoryId: "odnofaznaya-220v",
      priceRub: 275,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/trosovyy-podves-dlya-odnofaznogo-shinoprovoda-art-chyernyy-145-sm-100-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Тип крепления", value: "Накладной" },
        { label: "Цвет корпуса", value: "Черный" },
        { label: "Длина", value: "145 см" },
      ],
    },
    {
      id: "0У-00001557",
      title: "Крепление ART универсальное, 45×25 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 100,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/kreplenie-art-universalnoe-45-25-mm-200-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Тип крепления", value: "Универсальный" },
        { label: "Материал корпуса", value: "Металл" },
        { label: "Размер", value: "45×25 мм" },
      ],
    },
    {
      id: "0У-00001352",
      title: "Трековый светильник ART START поворотный однофазный чёрный, 30W, 4000К, 470×34×46 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 2090,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/trekovyy-svetilnik-art-start-povorotnyy-odnofaznyy-chyernyy-30w-4000k-470-34-46-mm-25-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Мощность", value: "30W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Световой поток", value: "2250Lm" },
      ],
    },
    {
      id: "0У-00001350",
      title: "Трековый светильник ART MONOLIT поворотный однофазный чёрный, 30W, 4000К, 470×34×46 мм",
      categoryId: "odnofaznaya-220v",
      priceRub: 2530,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/trekovyy-svetilnik-art-monolit-povorotnyy-odnofaznyy-chyernyy-30w-4000k-470-34-46-mm-25-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Напряжение", value: "220V" },
        { label: "Мощность", value: "30W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Световой поток", value: "2250Lm" },
      ],
    },
    {
      id: "0У-00006475",
      title: "Трековый поворотный однофазный светильник ART MONOLIT PRO черный, 30W, 4000К, 440×33",
      categoryId: "odnofaznaya-220v",
      priceRub: 2600,
      url: "https://eksmarket.ru/catalog/odnofaznaya-trekovaya-sistema-220v/trekovyy-povorotnyy-odnofaznyy-svetilnik-art-monolit-pro-chernyy-30w-4000k-440-33-40-sht/",
      availability: "нет данных",
      specs: [
        { label: "Мощность", value: "30W" },
        { label: "Температура свечения", value: "4000K" },
        { label: "Размер", value: "440×33 мм" },
      ],
    },
    {
      id: "0У-00006332",
      title: "Светильник GX53 OPTIMALIGHT GLASS трековый чёрный c креплением 80×104 мм (80×65 мм)",
      categoryId: "odnofaznaya-220v",
      priceRub: 520,
      url: "https://eksmarket.ru/catalog/svetilniki-gx53/svetilnik-gx53-optimalayt-glas-trekovyy-chyernyy-c-krepleniem-80-104mm-80-65mm-50-sht-kor/",
      availability: "нет данных",
      specs: [
        { label: "Тип", value: "светильник GX53" },
        { label: "Цвет", value: "чёрный" },
        { label: "Размер", value: "80×104 мм (80×65 мм)" },
      ],
    },
  ],
};
