export const homeAssets = [
  {
    assetKey: "hero-after",
    src: "/hero1.jpeg",
    alt: "Современный натяжной потолок с теневым профилем в квартире в Москве",
    width: 1600,
    height: 1067,
    section: "hero",
    priority: "high",
    sizesHint: "100vw",
    formatNote: "Основной hero-кадр для MVP",
    requiredForMvp: true,
    caption: "Основной кадр hero",
  },
  {
    assetKey: "proof-01",
    src: "/proj-shadow-1.jpeg",
    gallery: ["/proj-shadow-1.jpeg", "/proj-shadow-2.jpeg", "/proj-shadow-3.jpeg"],
    alt: "Натяжной потолок с теневым профилем в жилом интерьере",
    width: 1600,
    height: 1067,
    section: "proof",
    priority: "normal",
    sizesHint: "(max-width: 768px) 88vw, 560px",
    formatNote: "Proof image",
    requiredForMvp: true,
    caption: "Теневой профиль",
  },
  {
    assetKey: "proof-02",
    src: "/proj-float-1.jpeg",
    gallery: ["/proj-float-1.jpeg", "/proj-float-2.jpeg", "/proj-float-3.jpeg"],
    alt: "Парящий натяжной потолок с LED-подсветкой",
    width: 1600,
    height: 1067,
    section: "proof",
    priority: "normal",
    sizesHint: "(max-width: 768px) 88vw, 560px",
    formatNote: "Proof image",
    requiredForMvp: true,
    caption: "Парящий потолок",
  },
  {
    assetKey: "proof-03",
    src: "/proj-lines-1.jpeg",
    gallery: ["/proj-lines-1.jpeg", "/proj-lines-2.jpeg", "/proj-lines-3.jpeg"],
    alt: "Световые линии в натяжном потолке",
    width: 1600,
    height: 1067,
    section: "proof",
    priority: "normal",
    sizesHint: "(max-width: 768px) 88vw, 560px",
    formatNote: "Proof image",
    requiredForMvp: true,
    caption: "Световые линии",
  },
  {
    assetKey: "proof-04",
    src: "/proj-cornice-1.jpeg",
    gallery: ["/proj-cornice-1.jpeg", "/proj-cornice-2.jpeg", "/proj-cornice-3.jpeg"],
    alt: "Скрытый карниз в натяжном потолке",
    width: 1600,
    height: 1067,
    section: "proof",
    priority: "normal",
    sizesHint: "(max-width: 768px) 88vw, 560px",
    formatNote: "Proof image",
    requiredForMvp: true,
    caption: "Скрытый карниз",
  },
  {
    assetKey: "proof-05",
    src: "/proj-matte-1.jpeg",
    gallery: ["/proj-matte-1.jpeg", "/proj-matte-2.jpeg", "/proj-matte-3.jpeg"],
    alt: "Белый матовый натяжной потолок в квартире",
    width: 1600,
    height: 1067,
    section: "proof",
    priority: "low",
    sizesHint: "(max-width: 768px) 88vw, 560px",
    formatNote: "Optional proof image",
    requiredForMvp: false,
    caption: "Простой потолок",
  },
  {
    assetKey: "proof-06",
    src: "/proj-dome-1.jpeg",
    gallery: ["/proj-dome-1.jpeg", "/proj-dome-2.jpeg", "/proj-dome-3.jpeg"],
    alt: "Индивидуальный проект натяжного потолка со сложной геометрией",
    width: 1600,
    height: 1067,
    section: "proof",
    priority: "low",
    sizesHint: "(max-width: 768px) 88vw, 560px",
    formatNote: "Optional proof image",
    requiredForMvp: false,
    caption: "Индивидуальный проект",
  },
  {
    assetKey: "vladimir-portrait",
    src: "/about-master.jpeg",
    alt: "Владимир — мастер по натяжным потолкам",
    width: 1600,
    height: 1067,
    section: "trust",
    priority: "normal",
    sizesHint: "(max-width: 768px) 100vw, 520px",
    formatNote: "Founder portrait",
    requiredForMvp: true,
    caption: "Портрет Владимира",
  },
] as const;
