/**
 * T-046: `shortDescription` — одна строка для карточки смежной услуги.
 * Раньше во всех карточках стоял один и тот же текст-заглушка.
 */
export const serviceLinks = [
  {
    slug: "tenevoy-profil",
    shortDescription: "Ровная теневая линия вместо плинтуса, без видимого примыкания к стене.",
    label: "Теневой профиль",
    shortLabel: "Теневой профиль",
    href: "/uslugi/tenevoy-profil",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "paryashchie-potolki",
    shortDescription: "Светящийся контур по периметру — потолок словно висит в воздухе.",
    label: "Парящие потолки",
    shortLabel: "Парящие",
    href: "/uslugi/paryashchie-potolki",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "svetovye-linii",
    shortDescription: "Встроенные линии любой геометрии: замена люстрам и точечникам.",
    label: "Световые линии",
    shortLabel: "Световые линии",
    href: "/uslugi/svetovye-linii",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "trekovoe-osveshchenie",
    shortDescription: "Трек в потолке или накладной: свет можно двигать и перенаправлять.",
    label: "Трековое освещение",
    shortLabel: "Треки",
    href: "/uslugi/trekovoe-osveshchenie",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "skrytye-karnizy",
    shortDescription: "Ниша под карниз: шторы выходят прямо из потолка, без короба.",
    label: "Скрытые карнизы",
    shortLabel: "Карнизы",
    href: "/uslugi/skrytye-karnizy",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "prostye-potolki",
    shortDescription: "Ровный матовый или сатиновый потолок за один день.",
    label: "Простые потолки",
    shortLabel: "Простые",
    href: "/uslugi/prostye-potolki",
    priority: "medium",
    showInHeader: true, // ← было false, теперь в dropdown header
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "individualnye-proekty",
    shortDescription: "Многоуровневые и криволинейные конструкции по вашей схеме.",
    label: "Индивидуальные проекты",
    shortLabel: "Проекты",
    href: "/uslugi/individualnye-proekty",
    priority: "medium",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: false,
  },
  {
    slug: "prodazha-trekovogo-osveshcheniya",
    shortDescription: "Комплект света без монтажа: профиль, светильники, питание и лампы.",
    label: "Продажа трекового освещения",
    shortLabel: "Продажа треков",
    href: "/uslugi/prodazha-trekovogo-osveshcheniya",
    priority: "low",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: false,
    priceSectionEligible: false,
  },
  {
    slug: "svetoprozrachnye-potolki",
    shortDescription: "Равномерно светящееся полотно вместо привычных светильников.",
    label: "Светопрозрачные потолки",
    shortLabel: "Светопрозрачные",
    href: "/uslugi/svetoprozrachnye-potolki",
    priority: "low",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: false,
  },
] as const;
