export const serviceLinks = [
  {
    slug: "tenevoy-profil",
    label: "Теневой профиль",
    shortLabel: "Теневой профиль",
    href: "/uslugi/tenevoy-profil",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "paryashchie-potolki",
    label: "Парящие потолки",
    shortLabel: "Парящие",
    href: "/uslugi/paryashchie-potolki",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "svetovye-linii",
    label: "Световые линии",
    shortLabel: "Световые линии",
    href: "/uslugi/svetovye-linii",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "trekovoe-osveshchenie",
    label: "Трековое освещение",
    shortLabel: "Треки",
    href: "/uslugi/trekovoe-osveshchenie",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "skrytye-karnizy",
    label: "Скрытые карнизы",
    shortLabel: "Карнизы",
    href: "/uslugi/skrytye-karnizy",
    priority: "high",
    showInHeader: true,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "prostye-potolki",
    label: "Простые потолки",
    shortLabel: "Простые",
    href: "/uslugi/prostye-potolki",
    priority: "medium",
    showInHeader: true, // ← было false, теперь в dropdown header
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: true,
  },
  {
    slug: "individualnye-proekty",
    label: "Индивидуальные проекты",
    shortLabel: "Проекты",
    href: "/uslugi/individualnye-proekty",
    priority: "medium",
    showInHeader: false,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: false,
  },
  {
    slug: "prodazha-trekovogo-osveshcheniya",
    label: "Продажа трекового освещения",
    shortLabel: "Продажа треков",
    href: "/uslugi/prodazha-trekovogo-osveshcheniya",
    priority: "low",
    showInHeader: false,
    showInFooter: true,
    seoMentionEligible: false,
    priceSectionEligible: false,
  },
  {
    slug: "svetoprozrachnye-potolki",
    label: "Светопрозрачные потолки",
    shortLabel: "Светопрозрачные",
    href: "/uslugi/svetoprozrachnye-potolki",
    priority: "low",
    showInHeader: false,
    showInFooter: true,
    seoMentionEligible: true,
    priceSectionEligible: false,
  },
] as const;
